spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: b93d6c09d2c4e57c524c
            clientSecret: 16a2ca50f4c6a9ca495d00d4af499f689113ebe0t
          google:
            client-id: google-client-id
            client-secret: google-client-secret